services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: bugs_and_blossoms
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d bugs_and_blossoms"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:

