- generic [ref=e5]:
  - generic [ref=e6]:
    - heading "登录" [level=1] [ref=e7]
    - paragraph [ref=e8]: 登录后继续
  - generic [ref=e9]:
    - generic:
      - text: 邮箱
      - generic: "*"
    - generic [ref=e10]:
      - textbox "邮箱" [ref=e11]
      - group:
        - generic: 邮箱 *
  - generic [ref=e12]:
    - generic:
      - text: 密码
      - generic: "*"
    - generic [ref=e13]:
      - textbox "密码" [ref=e14]
      - group:
        - generic: 密码 *
  - button "登录" [ref=e15] [cursor=pointer]