#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

out="$root/internal/sqlc/schema.sql"
tmp="$(mktemp)"

{
  echo "-- Code generated by scripts/sqlc/export-schema.sh; DO NOT EDIT."
  echo "-- Source: modules/*/infrastructure/persistence/schema/*.sql"
  echo

  for module in iam orgunit jobcatalog staffing person; do
    dir="$root/modules/$module/infrastructure/persistence/schema"
    if [[ ! -d "$dir" ]]; then
      continue
    fi

    while IFS= read -r f; do
      echo "-- begin: ${f#"$root/"}"
      cat "$f"
      echo
      echo "-- end: ${f#"$root/"}"
      echo
    done < <(find "$dir" -maxdepth 1 -type f -name "*.sql" | LC_ALL=C sort)
  done
} >"$tmp"

mkdir -p "$(dirname "$out")"
mv "$tmp" "$out"
chmod 0644 "$out"
