#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

out="$root/internal/sqlc/schema.sql"
tmp="$(mktemp)"

list_modules() {
  local preferred=(iam orgunit jobcatalog staffing person)
  declare -A seen=()
  local module

  for module in "${preferred[@]}"; do
    if [[ -d "$root/modules/$module" ]]; then
      printf "%s\n" "$module"
      seen["$module"]=1
    fi
  done

  while IFS= read -r module; do
    if [[ -n "${seen[$module]:-}" ]]; then
      continue
    fi
    printf "%s\n" "$module"
  done < <(find "$root/modules" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | LC_ALL=C sort)
}

should_skip_schema_file() {
  local module="$1"
  local file="$2"
  local base
  base="$(basename "$file")"

  case "$module:$base" in
    orgunit:00023_*|orgunit:00024_*|orgunit:00025_*|orgunit:00026_*|orgunit:00027_*|orgunit:00028_*|orgunit:00029_*|orgunit:00030_*|orgunit:00031_*|orgunit:00032_*)
      return 0
      ;;
  esac

  return 1
}

{
  echo "-- Code generated by scripts/sqlc/export-schema.sh; DO NOT EDIT."
  echo "-- Source: modules/*/infrastructure/persistence/schema/*.sql"
  echo "-- Note: orgunit 00023-00032 are dedicated target bootstrap/runtime overlay files and are excluded from current runtime sqlc export."
  echo

  while IFS= read -r module; do
    dir="$root/modules/$module/infrastructure/persistence/schema"
    if [[ ! -d "$dir" ]]; then
      continue
    fi

    while IFS= read -r f; do
      if should_skip_schema_file "$module" "$f"; then
        continue
      fi
      echo "-- begin: ${f#"$root/"}"
      cat "$f"
      echo
      echo "-- end: ${f#"$root/"}"
      echo
    done < <(find "$dir" -maxdepth 1 -type f -name "*.sql" | LC_ALL=C sort)
  done < <(list_modules)
} >"$tmp"

mkdir -p "$(dirname "$out")"
mv "$tmp" "$out"
chmod 0644 "$out"
